name: Build Docker Image

on:
  push:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: pipelining
          password: ${{ secrets.DOCKERHUB_API_KEY }}

      - name: Build Docker image
        run: docker build -t pt-flutter:latest .

      - name: Push Docker image
        run: docker push pt-flutter:latest

